# Site settings
title: Eptitude blog 
tagline: A technical blog about life as an engineer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl"
   Because blogging is sharing, and sharing is caring about your fellow engineer, your fellow citizen and ultimately about making the world a better place.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eptitude.github.io" # the base hostname & protocol for your site
twitter_username: bongo
github_username:  ams0
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems: [jekyll-paginate]
